title: Ameer Dharamshi
name: Ameer Dharamshi
description: Hello there! Welcome to my personal site!
remote_theme: "mmistakes/minimal-mistakes@4.16.4"

plugins: 
  - jekyll-include-cache

locale: "en"
repository: "AmeerD/AmeerD.github.io"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

author:
  name: "Ameer Dharamshi"


minimal_mistakes_skin: "air"


