title: Ameer Dharamshi
name: Ameer Dharamshi TEST
description: Hello there! Welcome to my personal site!
remote_theme: "mmistakes/minimal-mistakes@4.16.4"

plugins: 
  - jekyll-include-cache

locale: "en"
repository: "AmeerD/AmeerD.github.io"

author:
  name: "Ameer Dharamshi"


minimal_mistakes_skin: "air"
